// Generated by tools/wav_to_pcm.py from mixkit-fuel-explosion-1705.wav -- do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

// 16-bit signed mono PCM, ready for M5.Speaker.playRaw().
constexpr uint32_t kBoomPcm_kSampleRate = 16000;
constexpr size_t   kBoomPcm_kSampleCount = 19200;
extern const int16_t kBoomPcm[];
