#!/usr/bin/env python3
"""
Convert a WAV file into a 16-bit mono PCM C array for M5Unified Speaker.playRaw().

Handles 16/24/32-bit integer PCM and WAVE_FORMAT_EXTENSIBLE, which the Python
stdlib `wave` module refuses. Downsamples by linear interpolation, trims to a
maximum duration, and applies a short fade-out so the clip does not click when
the DAC stops.

Usage:
    python3 tools/wav_to_pcm.py <input.wav> <output.h> <output.cpp> \
        [--rate 16000] [--seconds 1.2] [--symbol kBoomPcm]
"""

import argparse
import struct
import sys

# WAVE_FORMAT_EXTENSIBLE carries the real format tag in the first two bytes of
# its SubFormat GUID.
FMT_PCM = 0x0001
FMT_FLOAT = 0x0003
FMT_EXTENSIBLE = 0xFFFE


def read_chunks(data):
    if data[0:4] != b"RIFF" or data[8:12] != b"WAVE":
        raise ValueError("not a RIFF/WAVE file")
    pos = 12
    while pos + 8 <= len(data):
        cid = data[pos:pos + 4]
        (size,) = struct.unpack_from("<I", data, pos + 4)
        body = data[pos + 8:pos + 8 + size]
        yield cid, body
        pos += 8 + size + (size & 1)  # chunks are word-aligned


def parse_wav(path):
    with open(path, "rb") as fh:
        data = fh.read()

    fmt = None
    payload = None
    for cid, body in read_chunks(data):
        if cid == b"fmt " and fmt is None:
            tag, channels, rate, _byte_rate, _align, bits = struct.unpack_from("<HHIIHH", body, 0)
            if tag == FMT_EXTENSIBLE and len(body) >= 26:
                (tag,) = struct.unpack_from("<H", body, 24)
            fmt = (tag, channels, rate, bits)
        elif cid == b"data" and payload is None:
            payload = body

    if fmt is None or payload is None:
        raise ValueError("missing fmt or data chunk")
    return fmt, payload


def to_mono_float(fmt, payload):
    """Decode interleaved samples to a list of floats in [-1, 1), mixed to mono."""
    tag, channels, rate, bits = fmt
    width = bits // 8
    frame = width * channels
    frames = len(payload) // frame
    out = [0.0] * frames

    for i in range(frames):
        base = i * frame
        acc = 0.0
        for ch in range(channels):
            off = base + ch * width
            if tag == FMT_FLOAT:
                if bits == 32:
                    (v,) = struct.unpack_from("<f", payload, off)
                else:
                    (v,) = struct.unpack_from("<d", payload, off)
            elif bits == 8:
                v = (payload[off] - 128) / 128.0  # 8-bit WAV is unsigned
            elif bits == 16:
                (raw,) = struct.unpack_from("<h", payload, off)
                v = raw / 32768.0
            elif bits == 24:
                raw = int.from_bytes(payload[off:off + 3], "little", signed=True)
                v = raw / 8388608.0
            elif bits == 32:
                (raw,) = struct.unpack_from("<i", payload, off)
                v = raw / 2147483648.0
            else:
                raise ValueError("unsupported bit depth %d" % bits)
            acc += v
        out[i] = acc / channels

    return out, rate


def find_onset(samples, threshold=0.02):
    for i, v in enumerate(samples):
        if abs(v) > threshold:
            return i
    return 0


def resample(samples, src_rate, dst_rate):
    if src_rate == dst_rate:
        return list(samples)
    ratio = src_rate / dst_rate
    count = int(len(samples) / ratio)
    out = [0.0] * count
    for i in range(count):
        pos = i * ratio
        lo = int(pos)
        hi = min(lo + 1, len(samples) - 1)
        frac = pos - lo
        out[i] = samples[lo] * (1.0 - frac) + samples[hi] * frac
    return out


def normalise(samples, peak=0.92):
    hi = max((abs(v) for v in samples), default=0.0)
    if hi <= 0.0:
        return samples
    gain = peak / hi
    return [v * gain for v in samples]


def fade_out(samples, fade_len):
    n = min(fade_len, len(samples))
    for i in range(n):
        idx = len(samples) - n + i
        samples[idx] *= 1.0 - (i / n)
    return samples


def emit(path_h, path_cpp, symbol, pcm, rate, source_name):
    header_name = path_h.replace("\\", "/").rsplit("/", 1)[-1]
    with open(path_h, "w") as fh:
        fh.write(
            "// Generated by tools/wav_to_pcm.py from %s -- do not edit by hand.\n"
            "#pragma once\n\n"
            "#include <stddef.h>\n"
            "#include <stdint.h>\n\n"
            "// 16-bit signed mono PCM, ready for M5.Speaker.playRaw().\n"
            "constexpr uint32_t %s_kSampleRate = %u;\n"
            "constexpr size_t   %s_kSampleCount = %u;\n"
            "extern const int16_t %s[];\n" % (
                source_name, symbol, rate, symbol, len(pcm), symbol)
        )

    with open(path_cpp, "w") as fh:
        fh.write(
            "// Generated by tools/wav_to_pcm.py from %s -- do not edit by hand.\n"
            "#include \"assets/%s\"\n\n"
            "const int16_t %s[%s_kSampleCount] = {\n" % (
                source_name, header_name, symbol, symbol)
        )
        for i in range(0, len(pcm), 12):
            row = ", ".join("%6d" % v for v in pcm[i:i + 12])
            fh.write("    %s,\n" % row)
        fh.write("};\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("input")
    ap.add_argument("out_h")
    ap.add_argument("out_cpp")
    ap.add_argument("--rate", type=int, default=16000)
    ap.add_argument("--seconds", type=float, default=1.2)
    ap.add_argument("--symbol", default="kBoomPcm")
    args = ap.parse_args()

    fmt, payload = parse_wav(args.input)
    mono, rate = to_mono_float(fmt, payload)
    print("source: %d ch, %d Hz, %d bit, %d frames" % (fmt[1], fmt[2], fmt[3], len(mono)))

    mono = mono[find_onset(mono):]
    mono = resample(mono, rate, args.rate)
    mono = mono[:int(args.rate * args.seconds)]
    mono = normalise(mono)
    mono = fade_out(mono, int(args.rate * 0.08))

    pcm = [max(-32768, min(32767, int(round(v * 32767)))) for v in mono]
    emit(args.out_h, args.out_cpp, args.symbol, pcm, args.rate,
         args.input.rsplit("/", 1)[-1])
    print("wrote %d samples (%.2f s @ %d Hz, %.1f KB)" % (
        len(pcm), len(pcm) / args.rate, args.rate, len(pcm) * 2 / 1024))


if __name__ == "__main__":
    sys.exit(main())
